 services:
   # Service 1: Authentication
   auth-service:
     build:
       context: .
       dockerfile: backend/services/AuthenticationService/dockerfile
     env_file:
        - backend/services/AuthenticationService/.env
     ports:
       - "3001:3001"
     depends_on:
       - db

    # Service 2: Database
   db:
    image: postgres:15
    container_name: platform_db
    environment:
      POSTGRES_USER: adminUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
 volumes:
    postgres_data: