services:
  postgres:
    image: postgres:15
    container_name: engineering-platform-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: adminUser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminUser -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  notify-service:
    build:
      context: .
      dockerfile: backend/services/NotifyService/Dockerfile

    container_name: notify-service

    working_dir: /backend/services/NotifyService

    command: >
      sh -c "
      npm install &&
      npm run dev
      "

    volumes:
      - ./backend:/backend

    ports:
      - "3002:3002"
      - "50051:50051"

    env_file:
      - .env

    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: backend/services/AuthenticationService/Dockerfile

    container_name: auth-service

    working_dir: /backend/services/AuthenticationService

    command: >
      sh -c "
      npm install &&
      npm run dev
      "

    volumes:
      - ./backend:/backend
      - ./database:/database

    ports:
      - "3001:3001"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://adminUser:password@postgres:5432/auth_db

    depends_on:
      postgres:
        condition: service_healthy
      notify-service:
        condition: service_started

    restart: unless-stopped

  organization-service:
    build:
      context: .
      dockerfile: backend/services/OrganizationService/Dockerfile

    container_name: organization-service

    working_dir: /backend/services/OrganizationService

    command: >
      sh -c "
      npm install &&
      npm run dev
      "

    volumes:
      - ./backend:/backend
      - ./database:/database

    ports:
      - "3003:3003"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://adminUser:password@postgres:5432/auth_db

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

  repository-service:
    build:
      context: .
      dockerfile: backend/services/RepositoryService/Dockerfile

    container_name: repository-service

    working_dir: /backend/services/RepositoryService

    command: >
      sh -c "
      npm install &&
      npm run dev
      "

    volumes:
      - ./backend:/backend
      - ./database:/database

    ports:
      - "3004:3004"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://adminUser:password@postgres:5432/auth_db

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

volumes:
  postgres_data: