# Check the health of the organization-service
GET http://localhost:3003/api/v1/org/health HTTP/1.1




### Create Organization - SUCCESS
# Replace <YOUR_ACCESS_TOKEN> with a valid access token obtained from the Authentication Service
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMTQxNjg2LCJleHAiOjE3ODMxNDI1ODZ9.MjX-z0MYayxhmgDhfVw4NLYJNqsCfzvMryjRcC5crXM

{
  "name": "Engineering Intelligence Platform",
  "description": "Backend-first AI Governance Platform"
}




### Create Organization - Without Description
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMTQyNzAwLCJleHAiOjE3ODMxNDM2MDB9.IBZMJvjZ2-Lor-aUGyYPNkUI2aUeWcAzbsCUNFEQGkY

{
  "name": "OpenAI"
}




### Create Organization - Duplicate Name
# Expected: 409 Conflict (currently may return a generic error until custom errors are implemented)
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMTQyNzAwLCJleHAiOjE3ODMxNDM2MDB9.IBZMJvjZ2-Lor-aUGyYPNkUI2aUeWcAzbsCUNFEQGkY

{
  "name": "Engineering Intelligence Platform",
  "description": "Duplicate organization"
}




### Create Organization - Missing Authorization Header
# Expected: 401 Unauthorized
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json

{
  "name": "Unauthorized Org"
}




### Create Organization - Invalid Access Token
# Expected: 401 Unauthorized
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer invalid.jwt.token

{
  "name": "Invalid Token Org"
}




### Create Organization - Validation Error (Missing Name)
# Expected: 400 Bad Request
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMTQyNzAwLCJleHAiOjE3ODMxNDM2MDB9.IBZMJvjZ2-Lor-aUGyYPNkUI2aUeWcAzbsCUNFEQGkY

{
  "description": "Name field is required"
}




### Create Organization - Validation Error (Empty Name)
# Expected: 400 Bad Request
POST http://localhost:3003/api/v1/org/create-org HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMzE1NDU2LCJleHAiOjE3ODMzMTYzNTZ9.LAR8hqK5iJ_shXq0lPeyR_KNHmHHDOu_9x6lWXKOqAA

{
  "name": "Claude",
  "description": "Invalid organization"
}




### Get All Organizations
GET http://localhost:3003/api/v1/org/organizations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMzE1NDU2LCJleHAiOjE3ODMzMTYzNTZ9.LAR8hqK5iJ_shXq0lPeyR_KNHmHHDOu_9x6lWXKOqAA









### Get Organization By ID


@organizationId = cmr8rzz3x000018ocpba06woo
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXI1YWQ5YXQwMDAzMThwbXl4Z2J0czJ6IiwiaWF0IjoxNzgzMzE1NDU2LCJleHAiOjE3ODMzMTYzNTZ9.LAR8hqK5iJ_shXq0lPeyR_KNHmHHDOu_9x6lWXKOqAA


GET http://localhost:3003/api/v1/org/organizations/{{organizationId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
