#  Check the health of the auth-service
GET http://localhost:3001/api/v1/auth HTTP/1.1




### Check sign up rote is working or not
POST http://localhost:3001/api/v1/auth/signup HTTP/1.1
content-type: application/json

{
  "email": "ghoshfamily111@gmail.com",
  "password": "Password@123"
}




### 2. Verify OTP and Create User
POST http://localhost:3001/api/v1/auth/verify-otp HTTP/1.1
content-type: application/json

{
  "email": "test011@example.com",
  "otp": "487266"
}